(()=>{"use strict";const C=window.CYBER_CAFE_CONFIG||{},$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];const S={playlistId:"",player:null,ready:false,playing:false,shuffle:false,total:(C.startingMinutes||60)*60,remaining:(C.startingMinutes||60)*60,rate:C.hourlyRate||20,events:C.randomEvents!==false,sound:true,z:20,timer:null};const EVENTS=[["📶","Internet disconnected. Bhaiya router restart kar raha hai."],["🖨️","Printer mein paper nahi hai."],["💿","PC #03: CD burning 94%... nobody touch the computer."],["😤","Someone shouted: “Bhaiya net bahut slow hai!”"],["🎮","Counter-Strike LAN match started on PCs 04–09."],["📞","Yahoo Messenger BUZZ heard from the next computer."],["⚡","Voltage fluctuation. Everyone saved their Word document instantly."],["🧑‍💻","Bhaiya: “Computer band mat karna, download chal raha hai.”"],["📝","Someone is filling an entrance form with 3 minutes left."],["📀","A blank CD-R just sold for ₹20."],["🔌","Pen drive detected. Autorun.exe looks suspicious."],["🌐","Orkut is loading... very slowly."]];
function pid(v=""){v=v.trim();if(!v)return"";if(/^[\w-]{10,}$/.test(v)&&!v.includes("http"))return v;try{return new URL(v).searchParams.get("list")||""}catch{const m=v.match(/[?&]list=([\w-]+)/);return m?m[1]:""}}function beep(f=520,ms=70,t="square",vol=.025){if(!S.sound)return;try{const A=window.AudioContext||window.webkitAudioContext,ctx=beep.ctx||(beep.ctx=new A),o=ctx.createOscillator(),g=ctx.createGain();o.type=t;o.frequency.value=f;g.gain.value=vol;o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+ms/1000)}catch{}}function toast(msg,ic="💬"){let t=$("#toast");t.innerHTML=`<b>${ic} Cyber Cafe 2007</b><br>${msg}`;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),4200)}function front(w){S.z++;w.style.zIndex=S.z;$$('.task-btn').forEach(b=>b.classList.toggle('active',b.dataset.window===w.id))}function task(id,w){let b=$(`.task-btn[data-window="${id}"]`);if(!b){b=document.createElement('button');b.className='task-btn active';b.dataset.window=id;b.textContent=$('.titlebar span',w)?.textContent?.slice(0,28)||id;b.onclick=()=>w.classList.contains('hidden')?openW(id):front(w);$('#taskButtons').appendChild(b)}$$('.task-btn').forEach(x=>x.classList.toggle('active',x===b))}function openW(id){let w=document.getElementById(id);if(!w)return;w.classList.remove('hidden');front(w);task(id,w);$('#startMenu').classList.add('hidden');beep(620,45)}function closeW(id){let w=document.getElementById(id);if(!w)return;if(id==='youtubeWindow'&&S.ready&&S.playing)S.player.pauseVideo();w.classList.add('hidden');$(`.task-btn[data-window="${id}"]`)?.remove();beep(320,45)}
function windows(){$$('[data-open]').forEach(e=>e.onclick=()=>openW(e.dataset.open));$$('[data-close]').forEach(e=>e.onclick=()=>e.dataset.close==='setupModal'?$('#setupModal').classList.add('hidden'):closeW(e.dataset.close));$$('.app-window').forEach(w=>{w.onmousedown=()=>front(w);$('.minimize',w)&&($('.minimize',w).onclick=()=>{if(w.id==='youtubeWindow'&&S.ready&&S.playing)S.player.pauseVideo();w.classList.add('hidden')})});$$('.drag-handle').forEach(h=>{const w=h.closest('.app-window');let d=null;h.onpointerdown=e=>{if(e.target.closest('button')||innerWidth<760)return;front(w);const r=w.getBoundingClientRect();d={x:e.clientX-r.left,y:e.clientY-r.top};h.setPointerCapture(e.pointerId)};h.onpointermove=e=>{if(!d)return;w.style.left=Math.max(0,Math.min(innerWidth-w.offsetWidth,e.clientX-d.x))+'px';w.style.top=Math.max(0,Math.min(innerHeight-45-w.offsetHeight,e.clientY-d.y))+'px'};h.onpointerup=()=>d=null});$('#startBtn').onclick=e=>{e.stopPropagation();$('#startMenu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!e.target.closest('#startMenu')&&!e.target.closest('#startBtn'))$('#startMenu').classList.add('hidden')})}
function fmt(s){s=Math.max(0,Math.floor(s));return`${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}function clock(){const n=new Date;$('#taskClock').textContent=n.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}function tick(){S.remaining=Math.max(0,S.remaining-1);$('#remainingTime').textContent=fmt(S.remaining);$('#bill').textContent='₹'+(((S.total-S.remaining)/3600)*S.rate).toFixed(2);if(S.remaining===300)toast('Only 5 minutes left. Bhaiya is watching the clock.','⌛');if(S.remaining===0){$('#sessionStatus').textContent='TIME UP';toast('Time khatam. “Aur time chahiye?”','🧾')}}function reset(min=C.startingMinutes||60,rate=C.hourlyRate||20){S.rate=Math.max(1,rate);S.total=Math.max(600,min*60);S.remaining=S.total;$('#sessionStatus').textContent='ONLINE';$('#remainingTime').textContent=fmt(S.remaining);$('#bill').textContent='₹0.00'}function schedule(){clearTimeout(S.timer);if(!S.events)return;S.timer=setTimeout(()=>{const [i,m]=EVENTS[Math.floor(Math.random()*EVENTS.length)];toast(m,i);schedule()},18000+Math.random()*26000)}
function save(id){if(id)localStorage.setItem('cyberCafePlaylist',id);else localStorage.removeItem('cyberCafePlaylist');S.playlistId=id;const p=$('#setupPlaylist');if(p)p.value=id;status();if(S.ready)load()}function status(){$('#playlistStatus').textContent=S.playlistId?'CYBER CAFE RADIO • READY':'CYBER CAFE RADIO • OFFLINE';const empty=$('#playerEmpty');if(empty)empty.classList.toggle('hidden',!!S.playlistId&&S.ready)}function applySkin(name="classic",announce=false){
  const names={classic:"Classic Green",ocean:"Ocean Blue",fire:"Firestorm",purple:"Purple Haze",silver:"Silver XP",matrix:"Matrix"};
  if(!names[name])name="classic";
  const win=$('#winampWindow');if(win)win.dataset.skin=name;
  localStorage.setItem('cyberCafeWinampSkin',name);
  $$('.skin-card').forEach(b=>b.classList.toggle('active',b.dataset.skinChoice===name));
  const label=$('#activeSkinName');if(label)label.textContent=names[name];
  if(announce)toast(`${names[name]} skin applied.`,'🎨');
}
function setup(){
  S.playlistId=localStorage.getItem('cyberCafePlaylist')||C.defaultPlaylistId||'';
  const setupInput=$('#setupPlaylist');if(setupInput)setupInput.value=S.playlistId;
  const savedSkin=localStorage.getItem('cyberCafeWinampSkin')||'classic';applySkin(savedSkin,false);
  $$('.skin-card').forEach(b=>b.onclick=()=>applySkin(b.dataset.skinChoice,true));
  const saveSetup=$('#saveSetup');if(saveSetup)saveSetup.onclick=()=>{const id=pid($('#setupPlaylist').value);if(!id)return toast('That does not look like a playlist URL or ID.','⚠️');save(id);$('#setupModal').classList.add('hidden');openW('winampWindow');toast('Playlist connected. Winamp is ready.','🎵')};
  const demoSetup=$('#demoSetup');if(demoSetup)demoSetup.onclick=()=>$('#setupModal').classList.add('hidden');
  $('#eventToggle').onchange=e=>{S.events=e.target.checked;schedule()};
  $('#soundToggle').onchange=e=>S.sound=e.target.checked;
  $('#crtToggle').onchange=e=>document.body.classList.toggle('crt',e.target.checked);
  $('#addTen').onclick=()=>{S.total+=600;S.remaining+=600;$('#sessionStatus').textContent='ONLINE';toast('Bhaiya added 10 minutes. Pay later 😎','⌛')};
  $('#logOff').onclick=()=>$('#setupModal').classList.remove('hidden');
  $('#turnOff').onclick=()=>{document.body.innerHTML='<div style="height:100vh;background:#000;color:#f2b43c;display:grid;place-items:center;font:18px Tahoma;text-align:center"><div><div style="font-size:54px">🖥️</div><p>It is now safe to turn off your computer.</p><button onclick="location.reload()">Restart</button></div></div>'}
}
function apps(){$('#googleSearchBtn').onclick=()=>$('#searchResult').classList.remove('hidden');$('#fakeSearch').onkeydown=e=>e.key==='Enter'&&$('#googleSearchBtn').click();$('#postScrap').onclick=()=>{const x=$('#scrapInput'),v=x.value.trim();if(!v)return;const d=document.createElement('div');d.className='scrap';d.innerHTML='<b>You:</b> '+v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))+' <small>just now</small>';$('#scraps').prepend(d);x.value='';toast('Scrap posted. Waiting for testimonial.','💗')};$('#buzzBtn').onclick=()=>{let w=$('#yahooWindow');w.classList.remove('shake');void w.offsetWidth;w.classList.add('shake');$('#buzzText').textContent='You sent a BUZZ!!!';beep(180,140,'sawtooth',.04)};let burning=false;$('#burnCd').onclick=()=>{if(burning)return;burning=true;let p=0;$('#burnStatus').textContent='Burning... do NOT eject the CD.';const t=setInterval(()=>{p+=2+Math.floor(Math.random()*7);if(p>=100){p=100;clearInterval(t);burning=false;$('#burnStatus').textContent='Burn completed successfully. Write CD name with marker.';toast('CD ready: College Mix Final FINAL 💿','🔥')}$('#burnBar').style.width=p+'%'},180)};const cs=t=>{let p=document.createElement('p');p.textContent='> '+t;$('#csConsole').appendChild(p);$('#csConsole').scrollTop=$('#csConsole').scrollHeight};$('#csJoin').onclick=()=>{cs('Player cyber_cafe_07 joined Terrorist Force.');toast('LAN game joined. Ping: 5 ms.','🎮')};$('#csFire').onclick=()=>cs('Radio: FIRE IN THE HOLE!');$('#csHeadshot').onclick=()=>{cs('*** HEADSHOT *** cyber_cafe_07 -> PC_04');toast('HEADSHOT! PC #04 says you are screen watching.','🔫')}}
window.onYouTubeIframeAPIReady=()=>{S.player=new YT.Player('youtubePlayer',{width:'360',height:'203',playerVars:{playsinline:1,controls:0,rel:0,origin:location.origin==='null'?undefined:location.origin},events:{onReady:()=>{S.ready=true;S.player.setVolume(Number($('#volume').value||70));status();if(S.playlistId)load()},onStateChange:e=>{S.playing=e.data===YT.PlayerState.PLAYING;$('#winampWindow').classList.toggle('playing',S.playing);if(S.playing&&$('#youtubeWindow').classList.contains('hidden'))openW('youtubeWindow');track()},onError:e=>toast('YouTube player error '+e.data+'. Some videos may block embedding.','⚠️')}})};function load(){if(!S.ready||!S.playlistId)return;S.player.cuePlaylist({listType:'playlist',list:S.playlistId,index:0});$('#playerEmpty').classList.add('hidden');setTimeout(track,800)}function mm(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(Math.floor(s%60)).padStart(2,'0')}function fitTrackTitle(){const t=$('#trackTitle'),v=t?.parentElement;if(!t||!v)return;t.classList.remove('marquee');t.style.removeProperty('--scroll-distance');requestAnimationFrame(()=>{const distance=Math.max(0,t.scrollWidth-v.clientWidth);if(distance>4){t.style.setProperty('--scroll-distance',distance+'px');t.classList.add('marquee')}})}
function track(){if(!S.ready)return;try{const d=S.player.getVideoData(),cur=S.player.getCurrentTime()||0;$('#trackTitle').textContent=d?.title?d.title.toUpperCase():'CYBER CAFE PLAYLIST';$('#trackMeta').textContent=d?.author?d.author+' • YouTube':'YouTube playlist';$('#trackCounter').textContent=mm(cur);fitTrackTitle()}catch{}}
function playerControls(){$('#videoToggle').onclick=()=>openW('youtubeWindow');$('#playTrack').onclick=()=>{if(!S.playlistId){$('#setupModal').classList.remove('hidden');return toast('Connect the playlist once, then Winamp will remember it.','🎵')}openW('youtubeWindow');S.ready&&S.player.playVideo()};$('#pauseTrack').onclick=()=>S.ready&&S.player.pauseVideo();$('#stopTrack').onclick=()=>S.ready&&S.player.stopVideo();$('#nextTrack').onclick=()=>S.ready&&S.player.nextVideo();$('#prevTrack').onclick=()=>S.ready&&S.player.previousVideo();$('#shuffleTrack').onclick=()=>{S.shuffle=!S.shuffle;S.ready&&S.player.setShuffle?.(S.shuffle);toast('Shuffle '+(S.shuffle?'ON':'OFF'),'🔀')};$('#volume').oninput=e=>{let v=Number(e.target.value);$('#volumeLabel').textContent=v+'%';S.ready&&S.player.setVolume(v)};$('#seek').oninput=e=>{if(!S.ready)return;const d=S.player.getDuration?.()||0;if(d)S.player.seekTo(Number(e.target.value)/1000*d,true)};setInterval(()=>{if(!S.ready)return;try{const d=S.player.getDuration()||0,c=S.player.getCurrentTime()||0;if(d)$('#seek').value=Math.round(c/d*1000);if(S.playing)track()}catch{}},1000)}
window.addEventListener('resize',fitTrackTitle);
function init(){windows();setup();apps();playerControls();status();clock();reset(C.startingMinutes||60,C.hourlyRate||20);setInterval(clock,1000);setInterval(tick,1000);schedule();const done=()=>{$('#boot').classList.add('hidden');setTimeout(()=>{if(!S.playlistId)$('#setupModal').classList.remove('hidden')},250);beep(660,120,'sine')};setTimeout(done,2600);$('#skipBoot').onclick=done;if(S.playlistId)setTimeout(()=>openW('winampWindow'),3000)}document.addEventListener('DOMContentLoaded',init)})();
